// <auto-generated />
using System;
using EFCoreVIrgin.Data.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreVIrgin.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212074228_TimeTableRecords")]
    partial class TimeTableRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.ClassEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.ProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.StudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudentEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectEntityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentEntityId");

                    b.HasIndex("SubjectEntityId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.SubjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.TeacherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.TimeTableRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MInuteDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TimeTableRecord");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.ProfileEntity", b =>
                {
                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.StudentEntity", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("EFCoreVIrgin.Data.EF.Entity.ProfileEntity", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.StudentEntity", b =>
                {
                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.ClassEntity", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.StudentEntity", null)
                        .WithMany("Students")
                        .HasForeignKey("StudentEntityId");

                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.SubjectEntity", null)
                        .WithMany("Students")
                        .HasForeignKey("SubjectEntityId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.TimeTableRecordEntity", b =>
                {
                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.ClassEntity", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.SubjectEntity", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreVIrgin.Data.EF.Entity.TeacherEntity", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.ClassEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.StudentEntity", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EFCoreVIrgin.Data.EF.Entity.SubjectEntity", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
